<?php

namespace Etna\MathsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PolynomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PolynomeRepository extends EntityRepository
{
}
